### ISSUE TITLE
Documentation: requirements.txt usage

### ISSUE THREAD

**Issue by fbalak** [Tendrl/node_agent#80]
There should be documented how to use requirements.txt during installation. I ran into problem that I haven't installed python library ansible when I was trying to install node-agent from source according to documentation.

**Comment by r0h4n** [comment]
Can you provide the steps you had to take to resolve this issue? Also just to confirm, the python library missing was "ansible"?

**Comment by fbalak** [comment]
I just installed ansible library through pip into virtualenv.

**Comment by r0h4n** [comment]
ok, so "pip install ansible" fixed the problem?

The requirements.txt and the spec file both contain "ansible" as a dependency

@nnDarshan please try to reproduce this one

**Comment by mbukatov** [comment]
One problem here is that when one follow the docs and install the `node_agent` from sources, requirements are not installed since setup.py doesn't list them and I'm not running `pip install -r requirements.txt` neither (readme file doesn't mention this file at all).

The other problem is that `requirements.txt` file should be used to specify a requirements of whole python enviroments, not a single projects, see details in [install_requires vs Requirements files](https://packaging.python.org/requirements/#install-requires-vs-requirements-files)

For details how to specify requirements in `setup.py` via setuptools properly, see [install_requires](https://packaging.python.org/distributing/#install-requires)

**Comment by mbukatov** [comment]
In other words, this project is not following python packaging guidelines and can't be installed via pip without additional work. This is hindering both installation from the sources and creation and maintenance of rpm spec files.

When I do a review of all setup.py files in Tendrl group, I could propose a pull request (assuming the fix is easy) and remove any hack from our ansible playbooks at the same time.

**Comment by r0h4n** [comment]
Thanks @mbukatov , @nnDarshan please try to reproduce this and work with @mbukatov

**Comment by nnDarshan** [comment]
@fbalak @mbukatov @r0h4n The code for installing all the package dependencies was missing in node-agent setup script, have added the same. Also some documentation change was needed, have updated it.

@mbukatov thanks for pointing out about install_requires in setup.py
